version: '3'
services:
  geth:
    image: ethereum/client-go
    command: --datadir=/root/.ethereum/devchain  --http --http.addr 0.0.0.0 --http.corsdomain "*" --http.api "admin,debug,web3,eth,txpool,personal,ethash,miner,net" --allow-insecure-unlock 
    volumes:
      - ./genesis.json:/root/files/geth/genesis.json:ro
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
  web:
    build: .
    command: >
      sh -c   "python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/my_app_dir
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'my-app-db'
       MYSQL_USER: 'user#123$$'
       MYSQL_PASSWORD: 'password#123'
       MYSQL_ROOT_PASSWORD: 'password'




  
