version: '3'
services:
  geth:
    image: ethereum/client-go
    command: --datadir=/root/.ethereum/devchain  --http --http.addr 0.0.0.0 --http.corsdomain "*" --http.api "admin,debug,web3,eth,txpool,personal,ethash,miner,net" --allow-insecure-unlock init=/root/files/genesis.json
    volumes:
      - ./genesis.json:/root/files/geth/genesis.json:ro
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    restart: always
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true -Xmx512m -Xms512m -Djava.util.logging.config.file=/var/jenkins_home/log.properties"
    ports:
      - 8081:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/my_app_dir
    ports:
      - "8000:8000"
    depends_on:
      - db
      - web-migrate
  db:
    image: mysql
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'my-app-db'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: 'password'
       MYSQL_ROOT_PASSWORD: 'password'
  
  web-migrate:
    build: .
    command: python manage.py makemigrations && python manage.py migrate
    volumes:
      - .:/my_app_dir
    depends_on:
      - db


  
