version: '2'
services:
  geth:
    image: ethereum/client-go
    command: --datadir=/root/.ethereum/devchain --nodekeyhex=091bd6067cb4612df85d9c1ff85cc47f259ced4d4cd99816b14f35650f59c322 --rpcapi "db,personal,eth,net,web3" --rpccorsdomain='*' --networkid=1234 --rpc --rpcaddr="0.0.0.0" init=/root/files/genesis.json
    volumes:
      - ./genesis.json:/root/files/geth/genesis.json:ro
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    restart: always
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true -Xmx512m -Xms512m -Djava.util.logging.config.file=/var/jenkins_home/log.properties"
    ports:
      - 8081:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
  web:
    build: .
    environment:
      MYENV: EXAMPLE
    volumes:
      - .:/code

  web_migrate:
    extends:
      service: web
    command: python manage.py migrate

  web_run:
    extends:
      service: web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"



  
