# Generated by Django 4.0 on 2021-12-24 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='accountString',
            new_name='accountAddress',
        ),
    ]
