# Generated by Django 3.0.5 on 2021-11-18 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='DOB',
            new_name='dob',
        ),
    ]
