# Generated by Django 3.1.5 on 2021-12-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20211118_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
