# Generated by Django 4.0 on 2021-12-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_rename_accountstring_accounts_accountaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='electionN',
            field=models.CharField(default='EC1', max_length=250),
        ),
    ]
