# Generated by Django 4.0 on 2021-12-24 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_candidates_electionn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidates',
            name='electionN',
        ),
    ]
